# Generated by Django 6.0.6 on 2026-06-09 09:54

import challenges.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Display name for this file', max_length=200)),
                ('file', models.FileField(upload_to=challenges.models.challenge_file_upload_path)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='challenges.challenge')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Display text for the link', max_length=200)),
                ('url', models.URLField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='challenges.challenge')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
